blank_issues_enabled: true
contact_links:
  - name: "ğŸ™‹â€â™‚ï¸ Ask the community a question!"
    about: Have a question, that might not be a bug? Wondering how to solve a problem? Ask away!
    url: "https://github.com/charmbracelet/REPLACE_ME/discussions/new?category=q-a"
  - name: "ğŸ‰ Show us what you've made!"
    about: Have you built something using bubbletea, and want to show others? Post here!
    url: "https://github.com/charmbracelet/REPLACE_ME/discussions/categories/show-and-tell"
  - name: "ğŸ’¬ Discord chat"
    about: Chat on our Discord.
    url: "https://charm.sh/discord"
